# Generated by Django 5.0.1 on 2024-01-28 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
