# Generated by Django 5.0.1 on 2024-01-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0009_alter_user_gender_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
