# Generated by Django 5.0.1 on 2024-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0010_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
